name: "Setup action"
description: "Prepares for execution - set up Java, Kotlin, Gradle"

inputs:
  jdkVersion:
    description: "JDK version"
    required: false
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.jdkVersion }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.jdkVersion }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Cache Gradle packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Bootstrap gradlew
      run: ./gradle/bootstrap/bootstrap_gradlew.sh
      shell: bash
