# This workflow will release project with Gradle
name: Automated binary release

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 0 * * 5'
  # workflow_dispatch:
  #   inputs:
  #     scope:
  #       description: 'Specify scope that is to be used.'
  #       required: true
  #       type: choice
  #       options:
  #         - patch
  #         - minor
  #         - major
  #       default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

      - uses: ./.github/actions/setup

      - name: Build with Gradle
        run: ./gradlew build

      - name: Clean git
        run: git reset --hard HEAD

      - name: Set email
        run: git config user.email "formainframe@ibagroup.eu"

      - name: Set name
        run: git config user.name "For Mainframe"

      - name: Release with Gradle automatic
        run: ./gradlew release -x test -Prelease.useAutomaticVersion=true -Prelease.scope=${{ github.event.inputs.scope || env.DEFAULT_SCOPE }} -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_USERNAME
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          DEFAULT_SCOPE: 'patch'
          BUILD_NUMBER: ${{ github.run_number }}
          BRANCH_NAME: ${{ github.ref_name }}

      - uses: ./.github/actions/teardown
